#!/bin/bash

set -u -e

TEST_COVERAGE_MINIMUM=100

echo "Running pytest..."
python -m pytest --cov=src/helloworld --no-cov-on-fail --cov-fail-under=${TEST_COVERAGE_MINIMUM} --cov-branch --cov-report=term --cov-report=html tests/unit
